name: ci
on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and publish ${{ github.repository }}
        uses: macbre/push-to-ghcr@v16
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          extra_args: --tag ${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}